# This is default and very simple configuration file for Yasb. 
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --ahk"
  stop_command: "komorebic stop --ahk"
  reload_command: "komorebic stop --ahk && komorebic start --ahk"
bars:
  primary-bar:
    #screens: ["*"]
    screens: ["LG ULTRAWIDE", "VG27AQL1A"]
    enabled: true
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "System"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 48
    padding:
      top: 5
      left: 5
      bottom: 5
      right: 5
    widgets:
      left: [
        # "home",
        # "komorebi_control",
        # "komorebi_workspaces",
        "komorebi_active_layout",
        "shortcut1",
        "shortcut2",
        "km-toggle-lock",
        "weather",
        "apps",
        #"active_window",
      ]
      center: [
        "clock",
        "taskbar",
#        "komorebi_stack",
        "neuraspace_calendar",
      ]
      right: [
        # "media",
        "systray",
        "bluetooth",
        "microphone",
        "volume",
        "notifications",
        # "power_menu",
        
        ]
  secondary-bar:
    screens: ["\\\\.\\DISPLAY1"]
    enabled: true
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "System"
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_on_fullscreen: false
    dimensions:
      width: "100%"
      height: 48
    padding:
      top: 5
      left: 5
      bottom: 5
      right: 5
    widgets:
      left: [
        "komorebi_active_layout",
        "shortcut1",
        "km-toggle-lock",
        "weather",
      ]
      center: [
        "clock",
        "taskbar",
#        "komorebi_stack",
      ]
      right: [
        "systray",
        "bluetooth",
        "wifi",
        "battery",
        "microphone",
        "volume",
        # "notifications"
      ]
  right-bar:
    screens: ["\\\\.\\DISPLAY1"]
    enabled: false
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false

    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "System"
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_on_fullscreen: false
    dimensions:
      width: 400
      height: 48
    padding:
      top: 5
      left: 5
      bottom: 5
      right: 5
    widgets:
      right: [
        "systray",
        "bluetooth",
        "wifi",
        "battery",
        "volume",
      ]

widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udc3b</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "~\\Downloads" }
      - { title: "Documents", path: "~\\Documents" }
      - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: false
  shortcut1:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: ""
      app_list:
        - {icon: "\uf2d2", launch: "komorebic toggle-workspace-layer"}
      container_padding: 
        top: 0
        left: 4
        bottom: 0
        right: 4
      # label_shadow:
      #   enabled: true
      #   color: "black"
      #   radius: 3
      #   offset: [ 1, 1 ]
  shortcut2:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: ""
      app_list:
        - {icon: "\udb81\ude16", launch: "komorebic toggle-window-based-work-area-offset"}
      container_padding: 
        top: 0
        left: 4
        bottom: 0
        right: 4
  km-toggle-lock:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: ""
      app_list:
        - {icon: "\uf456", launch: "komorebic toggle-lock"}
      container_padding: 
        top: 0
        left: 4
        bottom: 0
        right: 4
      # label_shadow:
      #   enabled: true
      #   color: "black"
      #   radius: 3
      #   offset: [ 1, 1 ]
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 24
      monitor_exclusive: True
      animation:
        enabled: true
        duration: 200
        type: "fadeInOut"
      title_label:
        enabled: false
        show: "focused"
        min_length: 10
        max_length: 30
      ignore_apps:
        processes: ["wtq.exe", "wt.exe"]
        titles: ["ShareX - Editor menu"]
        classes: []
      container_padding: 
        top: 0
        left: 8
        bottom: 0
        right: 8
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist} - {title}"
      max_field_size:
        label: 40
        label_alt: 40
      show_thumbnail: true
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 80
      thumbnail_padding: 24
      thumbnail_corner_radius: 0
      thumbnail_edge_fade: true
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
      ignore_apps:
        title:
          - "ShareX - Editor Menu"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "\ueab0 {%a, %d %B \uf017 %H:%M:%S}"
      label_alt: "{%A, %d %B %Y, %d %b %H:%M}"
      timezones: []
      callbacks:
        on_left: "toggle_calendar"
      # on_right: "toggle_label"
  komorebi_control:
    type: "komorebi.control.KomorebiControlWidget"
    options:
      label: "<span>\udb80\uddd9</span>"
      icons:
        start: "\uead3"
        stop: "\uead7"
        reload: "\uead2"
      run_ahk: false
      run_whkd: true
      show_version: true
      komorebi_menu:
        blur: True
        round_corners: True
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'left'
        direction: 'down'
        offset_top: 6
        offset_left: 0
      # label_shadow:
      #   enabled: true
      #   color: "black"
      #   radius: 3
      #   offset: [ 1, 1 ]
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u23fc Offline"
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: "X"
      label_workspace_populated_btn: "\udb81\udc3e"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
          "scrolling",
        ]
      layout_icons:
        bsp: "\uebeb"
        columns: "\uebf7"
        rows: "\uec01"
        grid: "\udb81\udf58"
        vertical_stack: "\uebee"
        horizontal_stack: "\uebf0"
        ultrawide_vertical_stack: "\uebee"
        right_main_vertical_stack: "\uebf1"
        scrolling: "\udb80\udd37"
        monocle: "\uf06f"
        maximised: "\uf06f"
        floating: "\uf2d2"
        paused: "\udb83\udf89"
        tiling: "\udb81\ude40"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      callbacks:
        on_left: "toggle_layout_menu"
        on_middle: "toggle_monocle"
        on_right: "prev_layout"
  komorebi_stack:
    type: "komorebi.stack.StackWidget"
    options:
      label_offline: "Offline"
      label_window: ""
      label_window_active: ""
      label_no_window: "No Window"
      label_zero_index: false
      show_icons: "always"
      icon_size: 24
      max_length: 30
      max_length_active: 50
      max_length_ellipsis: ".."
      hide_if_offline: false
      show_only_stack: true
      animation: true
      enable_scroll_switching : true
      # container_shadow:
      #   enabled: true
      #   color: "#000000"
      #   offset: [0, 1]
      #   radius: 2
      # btn_shadow:
      #   enabled: true
      #   color: "#000000"
      #   offset: [0, 1]
      #   radius: 2
      # label_shadow:
      #   enabled: true
      #   color: "#000000"
      #   offset: [0, 1]
      #   radius: 2
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}  😎 {uv}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: env
      update_interval: 600
      hide_decimal: true
      location: env
      units: metric
      callbacks:
        on_left: "toggle_card"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\ue312"
        cloudyNight: "\ue311"
        rainyDay: "\ue308"
        rainyNight: "\ue333"
        snowyIcyDay: "\ue30a"
        snowyIcyNight: "\ue335"
        blizzardDay: "\udb83\udf36"
        blizzardNight: "\udb83\udf36"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\uebaa"
    weather_card:
      blur: True
      round_corners: True
      round_corners_type: "normal"
      border_color: "System"
      alignment: "right"
      direction: "down"
      icon_size: 64
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "<span>{icon}</span> {level}%"
      icons:
        normal: "\udb80\udf6c"
        muted: "\udb80\udf6d"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label: "{data}"
      image_icon_size: 24
      app_list:
        #- { icon: "\uf422", launch: "search" }
        - { icon: "\uf489", launch: "wt"} # launch terminal
        - { icon: "\udb83\ude10", launch: "\"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe\" --profile-directory=\"Profile 1\""}
        #- { icon: "\ueb03", launch: "cmd /c Taskmgr" }
        - { icon: "\udb80\udcd6", launch: "\"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe\" --profile-directory=\"Profile 0\"" }
        - { icon: "\uf232", launch: 'C:\Program Files\WindowsApps\5319275A.WhatsAppDesktop_2.2518.3.0_x64__cv1g1gvanyjgm\WhatsApp.exe' }
        - { icon: "\udb82\ude1e", launch: 'C:\Users\TiagoCorreia\AppData\Local\Programs\Microsoft VS Code\Code.exe' }
        - { icon: "\uec02", launch: 'C:\Users\TiagoCorreia\AppData\Local\fman\fman.exe' }
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [ 1, 1 ]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "⯇"
      label_expanded: "\uf00d"
      label_position: "left" # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      container_padding:
          left: 0
          top: 0
          right: 0
          bottom: 0
      btn_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "{device_name}"
      icons: 
        bluetooth_on: "\udb80\udcaf"
        bluetooth_off: "\udb80\udcb2"
        bluetooth_connected: "\udb80\udcb1"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "exec cmd.exe /c start ms-settings:network"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span>{ip_addr}"
      ethernet_icon: "\ueba9"
      wifi_icons: [
        "\udb82\udd2e",  # Icon for 0% strength
        "\udb82\udd1f",  # Icon for 1-24% strength 
        "\udb82\udd22",  # Icon for 25-49% strength
        "\udb82\udd25",  # Icon for 50-74% strength
        "\udb82\udd28"   # Icon for 75-100% strength
      ]
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]

  neuraspace_calendar:
    type: "yasb.google_meet.GoogleMeetWidget"
    options:
      env_var: "YASB_ICAL_URL"         # iCal URL environment variable name
      meeting_filter: "online"         # all | online | in_person
      timezone_name: "Europe/Lisbon"   # optional; IANA timezone
      horizon_hours: 12               # null=end-of-day, or number of hours
      next_time_format: "%H:%M"

      # Label placeholders
      label: "{next_time} {next_summary}"
      label_alt: "Today events ({countdown})"

      update_interval: 600000           # 10 minutes (ms)

      # Popup menu options
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0

      icons:
        online: "🔗"  # displayed when event is online
        time: "🕒"    # prefix for time in popup

      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"

      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

      animation:
        enabled: true
        type: "fadeInOut"
        duration: 200